class RingExecutor {

        public static void main(String[] args) {

                Ring ring1 = new Ring();
                ring1.materialType = "Gold";
                ring1.gemstoneType = "Diamond";
                ring1.ringSize = "7";
                ring1.color = "Yellow Gold";
                ring1.brand = "Tanishq";
                ring1.style = "Engagement";
                ring1.occasion = "Wedding";
                ring1.gender = "Female";
                ring1.platingType = "Gold Plated";
                ring1.weight = 5.5;

                System.out.println(" The Material Type of Ring is " + ring1.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring1.gemstoneType);
                System.out.println(" The Ring Size is " + ring1.ringSize);
                System.out.println(" The Color of Ring is " + ring1.color);
                System.out.println(" The Brand of Ring is " + ring1.brand);
                System.out.println(" The Style of Ring is " + ring1.style);
                System.out.println(" The Occasion of Ring is " + ring1.occasion);
                System.out.println(" The Gender of Ring is " + ring1.gender);
                System.out.println(" The Plating Type of Ring is " + ring1.platingType);
                System.out.println(" The Weight of Ring is " + ring1.weight);
                System.out.println("--------------------------------------");

                Ring ring2 = new Ring();
                ring2.materialType = "Silver";
                ring2.gemstoneType = "None";
                ring2.ringSize = "8";
                ring2.color = "Silver";
                ring2.brand = "Malabar";
                ring2.style = "Casual";
                ring2.occasion = "Daily Wear";
                ring2.gender = "Male";
                ring2.platingType = "Rhodium Plated";
                ring2.weight = 6.0;

                System.out.println(" The Material Type of Ring is " + ring2.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring2.gemstoneType);
                System.out.println(" The Ring Size is " + ring2.ringSize);
                System.out.println(" The Color of Ring is " + ring2.color);
                System.out.println(" The Brand of Ring is " + ring2.brand);
                System.out.println(" The Style of Ring is " + ring2.style);
                System.out.println(" The Occasion of Ring is " + ring2.occasion);
                System.out.println(" The Gender of Ring is " + ring2.gender);
                System.out.println(" The Plating Type of Ring is " + ring2.platingType);
                System.out.println(" The Weight of Ring is " + ring2.weight);
                System.out.println("--------------------------------------");

				Ring ring3 = new Ring();
                ring3.materialType = "Platinum";
                ring3.gemstoneType = "Emerald";
                ring3.ringSize = "6";
                ring3.color = "White";
                ring3.brand = "Kalyan Jewellers";
                ring3.style = "Luxury";
                ring3.occasion = "Party";
                ring3.gender = "Female";
                ring3.platingType = "None";
                ring3.weight = 4.8;

                System.out.println(" The Material Type of Ring is " + ring3.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring3.gemstoneType);
                System.out.println(" The Ring Size is " + ring3.ringSize);
                System.out.println(" The Color of Ring is " + ring3.color);
                System.out.println(" The Brand of Ring is " + ring3.brand);
                System.out.println(" The Style of Ring is " + ring3.style);
                System.out.println(" The Occasion of Ring is " + ring3.occasion);
                System.out.println(" The Gender of Ring is " + ring3.gender);
                System.out.println(" The Plating Type of Ring is " + ring3.platingType);
                System.out.println(" The Weight of Ring is " + ring3.weight);
                System.out.println("--------------------------------------");

                Ring ring4 = new Ring();
                ring4.materialType = "Gold";
                ring4.gemstoneType = "Ruby";
                ring4.ringSize = "7";
                ring4.color = "Rose Gold";
                ring4.brand = "PC Jeweller";
                ring4.style = "Traditional";
                ring4.occasion = "Festival";
                ring4.gender = "Female";
                ring4.platingType = "Gold Plated";
                ring4.weight = 5.2;

                System.out.println(" The Material Type of Ring is " + ring4.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring4.gemstoneType);
                System.out.println(" The Ring Size is " + ring4.ringSize);
                System.out.println(" The Color of Ring is " + ring4.color);
                System.out.println(" The Brand of Ring is " + ring4.brand);
                System.out.println(" The Style of Ring is " + ring4.style);
                System.out.println(" The Occasion of Ring is " + ring4.occasion);
                System.out.println(" The Gender of Ring is " + ring4.gender);
                System.out.println(" The Plating Type of Ring is " + ring4.platingType);
                System.out.println(" The Weight of Ring is " + ring4.weight);
                System.out.println("--------------------------------------");

                Ring ring5 = new Ring();
                ring5.materialType = "Silver";
                ring5.gemstoneType = "Sapphire";
                ring5.ringSize = "9";
                ring5.color = "Silver";
                ring5.brand = "CaratLane";
                ring5.style = "Modern";
                ring5.occasion = "Office";
                ring5.gender = "Unisex";
                ring5.platingType = "Rhodium Plated";
                ring5.weight = 6.3;

                System.out.println(" The Material Type of Ring is " + ring5.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring5.gemstoneType);
                System.out.println(" The Ring Size is " + ring5.ringSize);
                System.out.println(" The Color of Ring is " + ring5.color);
                System.out.println(" The Brand of Ring is " + ring5.brand);
                System.out.println(" The Style of Ring is " + ring5.style);
                System.out.println(" The Occasion of Ring is " + ring5.occasion);
                System.out.println(" The Gender of Ring is " + ring5.gender);
                System.out.println(" The Plating Type of Ring is " + ring5.platingType);
                System.out.println(" The Weight of Ring is " + ring5.weight);
                System.out.println("--------------------------------------");

                Ring ring6 = new Ring();
                ring6.materialType = "Platinum";
                ring6.gemstoneType = "Diamond";
                ring6.ringSize = "6";
                ring6.color = "White";
                ring6.brand = "Tanishq";
                ring6.style = "Engagement";
                ring6.occasion = "Wedding";
                ring6.gender = "Female";
                ring6.platingType = "None";
                ring6.weight = 4.5;

                System.out.println(" The Material Type of Ring is " + ring6.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring6.gemstoneType);
                System.out.println(" The Ring Size is " + ring6.ringSize);
                System.out.println(" The Color of Ring is " + ring6.color);
                System.out.println(" The Brand of Ring is " + ring6.brand);
                System.out.println(" The Style of Ring is " + ring6.style);
                System.out.println(" The Occasion of Ring is " + ring6.occasion);
                System.out.println(" The Gender of Ring is " + ring6.gender);
                System.out.println(" The Plating Type of Ring is " + ring6.platingType);
                System.out.println(" The Weight of Ring is " + ring6.weight);
                System.out.println("--------------------------------------");

                Ring ring7 = new Ring();
                ring7.materialType = "Gold";
                ring7.gemstoneType = "Emerald";
                ring7.ringSize = "7";
                ring7.color = "Yellow Gold";
                ring7.brand = "Malabar";
                ring7.style = "Traditional";
                ring7.occasion = "Festival";
                ring7.gender = "Female";
                ring7.platingType = "Gold Plated";
                ring7.weight = 5.8;

                System.out.println(" The Material Type of Ring is " + ring7.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring7.gemstoneType);
                System.out.println(" The Ring Size is " + ring7.ringSize);
                System.out.println(" The Color of Ring is " + ring7.color);
                System.out.println(" The Brand of Ring is " + ring7.brand);
                System.out.println(" The Style of Ring is " + ring7.style);
                System.out.println(" The Occasion of Ring is " + ring7.occasion);
                System.out.println(" The Gender of Ring is " + ring7.gender);
                System.out.println(" The Plating Type of Ring is " + ring7.platingType);
                System.out.println(" The Weight of Ring is " + ring7.weight);
                System.out.println("--------------------------------------");

                Ring ring8 = new Ring();
                ring8.materialType = "Silver";
                ring8.gemstoneType = "None";
                ring8.ringSize = "8";
                ring8.color = "Silver";
                ring8.brand = "CaratLane";
                ring8.style = "Casual";
                ring8.occasion = "Daily Wear";
                ring8.gender = "Unisex";
                ring8.platingType = "Rhodium Plated";
                ring8.weight = 6.5;

                System.out.println(" The Material Type of Ring is " + ring8.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring8.gemstoneType);
                System.out.println(" The Ring Size is " + ring8.ringSize);
                System.out.println(" The Color of Ring is " + ring8.color);
                System.out.println(" The Brand of Ring is " + ring8.brand);
                System.out.println(" The Style of Ring is " + ring8.style);
                System.out.println(" The Occasion of Ring is " + ring8.occasion);
                System.out.println(" The Gender of Ring is " + ring8.gender);
                System.out.println(" The Plating Type of Ring is " + ring8.platingType);
                System.out.println(" The Weight of Ring is " + ring8.weight);
                System.out.println("--------------------------------------");

                Ring ring9 = new Ring();
                ring9.materialType = "Gold";
                ring9.gemstoneType = "Ruby";
                ring9.ringSize = "7";
                ring9.color = "Rose Gold";
                ring9.brand = "Kalyan Jewellers";
                ring9.style = "Designer";
                ring9.occasion = "Party";
                ring9.gender = "Female";
                ring9.platingType = "Gold Plated";
                ring9.weight = 5.1;

                System.out.println(" The Material Type of Ring is " + ring9.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring9.gemstoneType);
                System.out.println(" The Ring Size is " + ring9.ringSize);
                System.out.println(" The Color of Ring is " + ring9.color);
                System.out.println(" The Brand of Ring is " + ring9.brand);
                System.out.println(" The Style of Ring is " + ring9.style);
                System.out.println(" The Occasion of Ring is " + ring9.occasion);
                System.out.println(" The Gender of Ring is " + ring9.gender);
                System.out.println(" The Plating Type of Ring is " + ring9.platingType);
                System.out.println(" The Weight of Ring is " + ring9.weight);
                System.out.println("--------------------------------------");

                Ring ring10 = new Ring();
                ring10.materialType = "Platinum";
                ring10.gemstoneType = "Sapphire";
                ring10.ringSize = "6";
                ring10.color = "White";
                ring10.brand = "PC Jeweller";
                ring10.style = "Luxury";
                ring10.occasion = "Office";
                ring10.gender = "Male";
                ring10.platingType = "None";
                ring10.weight = 4.9;

                System.out.println(" The Material Type of Ring is " + ring10.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring10.gemstoneType);
                System.out.println(" The Ring Size is " + ring10.ringSize);
                System.out.println(" The Color of Ring is " + ring10.color);
                System.out.println(" The Brand of Ring is " + ring10.brand);
                System.out.println(" The Style of Ring is " + ring10.style);
                System.out.println(" The Occasion of Ring is " + ring10.occasion);
                System.out.println(" The Gender of Ring is " + ring10.gender);
                System.out.println(" The Plating Type of Ring is " + ring10.platingType);
                System.out.println(" The Weight of Ring is " + ring10.weight);
                System.out.println("--------------------------------------");

                Ring ring11 = new Ring();
                ring11.materialType = "Gold";
                ring11.gemstoneType = "Diamond";
                ring11.ringSize = "7";
                ring11.color = "Yellow Gold";
                ring11.brand = "Tanishq";
                ring11.style = "Wedding";
                ring11.occasion = "Marriage";
                ring11.gender = "Female";
                ring11.platingType = "Gold Plated";
                ring11.weight = 5.7;

                System.out.println(" The Material Type of Ring is " + ring11.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring11.gemstoneType);
                System.out.println(" The Ring Size is " + ring11.ringSize);
                System.out.println(" The Color of Ring is " + ring11.color);
                System.out.println(" The Brand of Ring is " + ring11.brand);
                System.out.println(" The Style of Ring is " + ring11.style);
                System.out.println(" The Occasion of Ring is " + ring11.occasion);
                System.out.println(" The Gender of Ring is " + ring11.gender);
                System.out.println(" The Plating Type of Ring is " + ring11.platingType);
                System.out.println(" The Weight of Ring is " + ring11.weight);
                System.out.println("--------------------------------------");

                Ring ring12 = new Ring();
                ring12.materialType = "Silver";
                ring12.gemstoneType = "None";
                ring12.ringSize = "8";
                ring12.color = "Silver";
                ring12.brand = "Malabar";
                ring12.style = "Casual";
                ring12.occasion = "Daily Wear";
                ring12.gender = "Male";
                ring12.platingType = "Rhodium Plated";
                ring12.weight = 6.2;

                System.out.println(" The Material Type of Ring is " + ring12.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring12.gemstoneType);
                System.out.println(" The Ring Size is " + ring12.ringSize);
                System.out.println(" The Color of Ring is " + ring12.color);
                System.out.println(" The Brand of Ring is " + ring12.brand);
                System.out.println(" The Style of Ring is " + ring12.style);
                System.out.println(" The Occasion of Ring is " + ring12.occasion);
                System.out.println(" The Gender of Ring is " + ring12.gender);
                System.out.println(" The Plating Type of Ring is " + ring12.platingType);
                System.out.println(" The Weight of Ring is " + ring12.weight);
                System.out.println("--------------------------------------");
				
				Ring ring13 = new Ring();
                ring13.materialType = "Platinum";
                ring13.gemstoneType = "Emerald";
                ring13.ringSize = "6";
                ring13.color = "White";
                ring13.brand = "Kalyan Jewellers";
                ring13.style = "Luxury";
                ring13.occasion = "Party";
                ring13.gender = "Female";
                ring13.platingType = "None";
                ring13.weight = 4.7;

                System.out.println(" The Material Type of Ring is " + ring13.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring13.gemstoneType);
                System.out.println(" The Ring Size is " + ring13.ringSize);
                System.out.println(" The Color of Ring is " + ring13.color);
                System.out.println(" The Brand of Ring is " + ring13.brand);
                System.out.println(" The Style of Ring is " + ring13.style);
                System.out.println(" The Occasion of Ring is " + ring13.occasion);
                System.out.println(" The Gender of Ring is " + ring13.gender);
                System.out.println(" The Plating Type of Ring is " + ring13.platingType);
                System.out.println(" The Weight of Ring is " + ring13.weight);
                System.out.println("--------------------------------------");

                Ring ring14 = new Ring();
                ring14.materialType = "Gold";
                ring14.gemstoneType = "Ruby";
                ring14.ringSize = "7";
                ring14.color = "Rose Gold";
                ring14.brand = "PC Jeweller";
                ring14.style = "Traditional";
                ring14.occasion = "Festival";
                ring14.gender = "Female";
                ring14.platingType = "Gold Plated";
                ring14.weight = 5.3;

                System.out.println(" The Material Type of Ring is " + ring14.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring14.gemstoneType);
                System.out.println(" The Ring Size is " + ring14.ringSize);
                System.out.println(" The Color of Ring is " + ring14.color);
                System.out.println(" The Brand of Ring is " + ring14.brand);
                System.out.println(" The Style of Ring is " + ring14.style);
                System.out.println(" The Occasion of Ring is " + ring14.occasion);
                System.out.println(" The Gender of Ring is " + ring14.gender);
                System.out.println(" The Plating Type of Ring is " + ring14.platingType);
                System.out.println(" The Weight of Ring is " + ring14.weight);
                System.out.println("--------------------------------------");

                Ring ring15 = new Ring();
                ring15.materialType = "Silver";
                ring15.gemstoneType = "Sapphire";
                ring15.ringSize = "9";
                ring15.color = "Silver";
                ring15.brand = "CaratLane";
                ring15.style = "Modern";
                ring15.occasion = "Office";
                ring15.gender = "Unisex";
                ring15.platingType = "Rhodium Plated";
                ring15.weight = 6.4;

                System.out.println(" The Material Type of Ring is " + ring15.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring15.gemstoneType);
                System.out.println(" The Ring Size is " + ring15.ringSize);
                System.out.println(" The Color of Ring is " + ring15.color);
                System.out.println(" The Brand of Ring is " + ring15.brand);
                System.out.println(" The Style of Ring is " + ring15.style);
                System.out.println(" The Occasion of Ring is " + ring15.occasion);
                System.out.println(" The Gender of Ring is " + ring15.gender);
                System.out.println(" The Plating Type of Ring is " + ring15.platingType);
                System.out.println(" The Weight of Ring is " + ring15.weight);
                System.out.println("--------------------------------------");

                Ring ring16 = new Ring();
                ring16.materialType = "Platinum";
                ring16.gemstoneType = "Diamond";
                ring16.ringSize = "6";
                ring16.color = "White";
                ring16.brand = "Tanishq";
                ring16.style = "Luxury";
                ring16.occasion = "Wedding";
                ring16.gender = "Female";
                ring16.platingType = "None";
                ring16.weight = 4.6;

                System.out.println(" The Material Type of Ring is " + ring16.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring16.gemstoneType);
                System.out.println(" The Ring Size is " + ring16.ringSize);
                System.out.println(" The Color of Ring is " + ring16.color);
                System.out.println(" The Brand of Ring is " + ring16.brand);
                System.out.println(" The Style of Ring is " + ring16.style);
                System.out.println(" The Occasion of Ring is " + ring16.occasion);
                System.out.println(" The Gender of Ring is " + ring16.gender);
                System.out.println(" The Plating Type of Ring is " + ring16.platingType);
                System.out.println(" The Weight of Ring is " + ring16.weight);
                System.out.println("--------------------------------------");

                Ring ring17 = new Ring();
                ring17.materialType = "Gold";
                ring17.gemstoneType = "Emerald";
                ring17.ringSize = "7";
                ring17.color = "Yellow Gold";
                ring17.brand = "Malabar";
                ring17.style = "Traditional";
                ring17.occasion = "Festival";
                ring17.gender = "Female";
                ring17.platingType = "Gold Plated";
                ring17.weight = 5.9;

                System.out.println(" The Material Type of Ring is " + ring17.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring17.gemstoneType);
                System.out.println(" The Ring Size is " + ring17.ringSize);
                System.out.println(" The Color of Ring is " + ring17.color);
                System.out.println(" The Brand of Ring is " + ring17.brand);
                System.out.println(" The Style of Ring is " + ring17.style);
                System.out.println(" The Occasion of Ring is " + ring17.occasion);
                System.out.println(" The Gender of Ring is " + ring17.gender);
                System.out.println(" The Plating Type of Ring is " + ring17.platingType);
                System.out.println(" The Weight of Ring is " + ring17.weight);
                System.out.println("--------------------------------------");

                Ring ring18 = new Ring();
                ring18.materialType = "Silver";
                ring18.gemstoneType = "None";
                ring18.ringSize = "8";
                ring18.color = "Silver";
                ring18.brand = "CaratLane";
                ring18.style = "Casual";
                ring18.occasion = "Daily Wear";
                ring18.gender = "Unisex";
                ring18.platingType = "Rhodium Plated";
                ring18.weight = 6.6;

                System.out.println(" The Material Type of Ring is " + ring18.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring18.gemstoneType);
                System.out.println(" The Ring Size is " + ring18.ringSize);
                System.out.println(" The Color of Ring is " + ring18.color);
                System.out.println(" The Brand of Ring is " + ring18.brand);
                System.out.println(" The Style of Ring is " + ring18.style);
                System.out.println(" The Occasion of Ring is " + ring18.occasion);
                System.out.println(" The Gender of Ring is " + ring18.gender);
                System.out.println(" The Plating Type of Ring is " + ring18.platingType);
                System.out.println(" The Weight of Ring is " + ring18.weight);
                System.out.println("--------------------------------------");

                Ring ring19 = new Ring();
                ring19.materialType = "Gold";
                ring19.gemstoneType = "Ruby";
                ring19.ringSize = "7";
                ring19.color = "Rose Gold";
                ring19.brand = "Kalyan Jewellers";
                ring19.style = "Designer";
                ring19.occasion = "Party";
                ring19.gender = "Female";
                ring19.platingType = "Gold Plated";
                ring19.weight = 5.0;

                System.out.println(" The Material Type of Ring is " + ring19.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring19.gemstoneType);
                System.out.println(" The Ring Size is " + ring19.ringSize);
                System.out.println(" The Color of Ring is " + ring19.color);
                System.out.println(" The Brand of Ring is " + ring19.brand);
                System.out.println(" The Style of Ring is " + ring19.style);
                System.out.println(" The Occasion of Ring is " + ring19.occasion);
                System.out.println(" The Gender of Ring is " + ring19.gender);
                System.out.println(" The Plating Type of Ring is " + ring19.platingType);
                System.out.println(" The Weight of Ring is " + ring19.weight);
                System.out.println("--------------------------------------");

                Ring ring20 = new Ring();
                ring20.materialType = "Platinum";
                ring20.gemstoneType = "Sapphire";
                ring20.ringSize = "6";
                ring20.color = "White";
                ring20.brand = "PC Jeweller";
                ring20.style = "Luxury";
                ring20.occasion = "Office";
                ring20.gender = "Male";
                ring20.platingType = "None";
                ring20.weight = 4.8;

                System.out.println(" The Material Type of Ring is " + ring20.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring20.gemstoneType);
                System.out.println(" The Ring Size is " + ring20.ringSize);
                System.out.println(" The Color of Ring is " + ring20.color);
                System.out.println(" The Brand of Ring is " + ring20.brand);
                System.out.println(" The Style of Ring is " + ring20.style);
                System.out.println(" The Occasion of Ring is " + ring20.occasion);
                System.out.println(" The Gender of Ring is " + ring20.gender);
                System.out.println(" The Plating Type of Ring is " + ring20.platingType);
                System.out.println(" The Weight of Ring is " + ring20.weight);
                System.out.println("--------------------------------------");

                Ring ring21 = new Ring();
                ring21.materialType = "Gold";
                ring21.gemstoneType = "Diamond";
                ring21.ringSize = "7";
                ring21.color = "Yellow Gold";
                ring21.brand = "Tanishq";
                ring21.style = "Engagement";
                ring21.occasion = "Wedding";
                ring21.gender = "Female";
                ring21.platingType = "Gold Plated";
                ring21.weight = 5.6;

                System.out.println(" The Material Type of Ring is " + ring21.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring21.gemstoneType);
                System.out.println(" The Ring Size is " + ring21.ringSize);
                System.out.println(" The Color of Ring is " + ring21.color);
                System.out.println(" The Brand of Ring is " + ring21.brand);
                System.out.println(" The Style of Ring is " + ring21.style);
                System.out.println(" The Occasion of Ring is " + ring21.occasion);
                System.out.println(" The Gender of Ring is " + ring21.gender);
                System.out.println(" The Plating Type of Ring is " + ring21.platingType);
                System.out.println(" The Weight of Ring is " + ring21.weight);
                System.out.println("--------------------------------------");

                Ring ring22 = new Ring();
                ring22.materialType = "Silver";
                ring22.gemstoneType = "None";
                ring22.ringSize = "8";
                ring22.color = "Silver";
                ring22.brand = "Malabar";
                ring22.style = "Casual";
                ring22.occasion = "Daily Wear";
                ring22.gender = "Male";
                ring22.platingType = "Rhodium Plated";
                ring22.weight = 6.1;

                System.out.println(" The Material Type of Ring is " + ring22.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring22.gemstoneType);
                System.out.println(" The Ring Size is " + ring22.ringSize);
                System.out.println(" The Color of Ring is " + ring22.color);
                System.out.println(" The Brand of Ring is " + ring22.brand);
                System.out.println(" The Style of Ring is " + ring22.style);
                System.out.println(" The Occasion of Ring is " + ring22.occasion);
                System.out.println(" The Gender of Ring is " + ring22.gender);	
                System.out.println(" The Plating Type of Ring is " + ring22.platingType);
                System.out.println(" The Weight of Ring is " + ring22.weight);
                System.out.println("--------------------------------------");
				
				Ring ring23 = new Ring();
                ring23.materialType = "Platinum";
                ring23.gemstoneType = "Emerald";
                ring23.ringSize = "6";
                ring23.color = "White";
                ring23.brand = "Kalyan Jewellers";
                ring23.style = "Luxury";
                ring23.occasion = "Party";
                ring23.gender = "Female";
                ring23.platingType = "None";
                ring23.weight = 4.7;

                System.out.println(" The Material Type of Ring is " + ring23.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring23.gemstoneType);
                System.out.println(" The Ring Size is " + ring23.ringSize);
                System.out.println(" The Color of Ring is " + ring23.color);
                System.out.println(" The Brand of Ring is " + ring23.brand);
                System.out.println(" The Style of Ring is " + ring23.style);
                System.out.println(" The Occasion of Ring is " + ring23.occasion);
                System.out.println(" The Gender of Ring is " + ring23.gender);
                System.out.println(" The Plating Type of Ring is " + ring23.platingType);
                System.out.println(" The Weight of Ring is " + ring23.weight);
                System.out.println("--------------------------------------");

                Ring ring24 = new Ring();
                ring24.materialType = "Gold";
                ring24.gemstoneType = "Ruby";
                ring24.ringSize = "7";
                ring24.color = "Rose Gold";
                ring24.brand = "PC Jeweller";
                ring24.style = "Traditional";
                ring24.occasion = "Festival";
                ring24.gender = "Female";
                ring24.platingType = "Gold Plated";
                ring24.weight = 5.2;

                System.out.println(" The Material Type of Ring is " + ring24.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring24.gemstoneType);
                System.out.println(" The Ring Size is " + ring24.ringSize);
                System.out.println(" The Color of Ring is " + ring24.color);
                System.out.println(" The Brand of Ring is " + ring24.brand);
                System.out.println(" The Style of Ring is " + ring24.style);
                System.out.println(" The Occasion of Ring is " + ring24.occasion);
                System.out.println(" The Gender of Ring is " + ring24.gender);
                System.out.println(" The Plating Type of Ring is " + ring24.platingType);
                System.out.println(" The Weight of Ring is " + ring24.weight);
                System.out.println("--------------------------------------");

                Ring ring25 = new Ring();
                ring25.materialType = "Silver";
                ring25.gemstoneType = "Sapphire";
                ring25.ringSize = "9";
                ring25.color = "Silver";
                ring25.brand = "CaratLane";
                ring25.style = "Modern";
                ring25.occasion = "Office";
                ring25.gender = "Unisex";
                ring25.platingType = "Rhodium Plated";
                ring25.weight = 6.3;

                System.out.println(" The Material Type of Ring is " + ring25.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring25.gemstoneType);
                System.out.println(" The Ring Size is " + ring25.ringSize);
                System.out.println(" The Color of Ring is " + ring25.color);
                System.out.println(" The Brand of Ring is " + ring25.brand);
                System.out.println(" The Style of Ring is " + ring25.style);
                System.out.println(" The Occasion of Ring is " + ring25.occasion);
                System.out.println(" The Gender of Ring is " + ring25.gender);
                System.out.println(" The Plating Type of Ring is " + ring25.platingType);
                System.out.println(" The Weight of Ring is " + ring25.weight);
                System.out.println("--------------------------------------");

                Ring ring26 = new Ring();
                ring26.materialType = "Platinum";
                ring26.gemstoneType = "Diamond";
                ring26.ringSize = "6";
                ring26.color = "White";
                ring26.brand = "Tanishq";
                ring26.style = "Luxury";
                ring26.occasion = "Wedding";
                ring26.gender = "Female";
                ring26.platingType = "None";
                ring26.weight = 4.6;

                System.out.println(" The Material Type of Ring is " + ring26.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring26.gemstoneType);
                System.out.println(" The Ring Size is " + ring26.ringSize);
                System.out.println(" The Color of Ring is " + ring26.color);
                System.out.println(" The Brand of Ring is " + ring26.brand);
                System.out.println(" The Style of Ring is " + ring26.style);
                System.out.println(" The Occasion of Ring is " + ring26.occasion);
                System.out.println(" The Gender of Ring is " + ring26.gender);
                System.out.println(" The Plating Type of Ring is " + ring26.platingType);
                System.out.println(" The Weight of Ring is " + ring26.weight);
                System.out.println("--------------------------------------");

                Ring ring27 = new Ring();
                ring27.materialType = "Gold";
                ring27.gemstoneType = "Emerald";
                ring27.ringSize = "7";
                ring27.color = "Yellow Gold";
                ring27.brand = "Malabar";
                ring27.style = "Traditional";
                ring27.occasion = "Festival";
                ring27.gender = "Female";
                ring27.platingType = "Gold Plated";
                ring27.weight = 5.9;

                System.out.println(" The Material Type of Ring is " + ring27.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring27.gemstoneType);
                System.out.println(" The Ring Size is " + ring27.ringSize);
                System.out.println(" The Color of Ring is " + ring27.color);
                System.out.println(" The Brand of Ring is " + ring27.brand);
                System.out.println(" The Style of Ring is " + ring27.style);
                System.out.println(" The Occasion of Ring is " + ring27.occasion);
                System.out.println(" The Gender of Ring is " + ring27.gender);
                System.out.println(" The Plating Type of Ring is " + ring27.platingType);
                System.out.println(" The Weight of Ring is " + ring27.weight);
                System.out.println("--------------------------------------");

                Ring ring28 = new Ring();
                ring28.materialType = "Silver";
                ring28.gemstoneType = "None";
                ring28.ringSize = "8";
                ring28.color = "Silver";
                ring28.brand = "CaratLane";
                ring28.style = "Casual";
                ring28.occasion = "Daily Wear";
                ring28.gender = "Unisex";
                ring28.platingType = "Rhodium Plated";
                ring28.weight = 6.6;

                System.out.println(" The Material Type of Ring is " + ring28.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring28.gemstoneType);
                System.out.println(" The Ring Size is " + ring28.ringSize);
                System.out.println(" The Color of Ring is " + ring28.color);
                System.out.println(" The Brand of Ring is " + ring28.brand);
                System.out.println(" The Style of Ring is " + ring28.style);
                System.out.println(" The Occasion of Ring is " + ring28.occasion);
                System.out.println(" The Gender of Ring is " + ring28.gender);
                System.out.println(" The Plating Type of Ring is " + ring28.platingType);
                System.out.println(" The Weight of Ring is " + ring28.weight);
                System.out.println("--------------------------------------");

                Ring ring29 = new Ring();
                ring29.materialType = "Gold";
                ring29.gemstoneType = "Ruby";
                ring29.ringSize = "7";
                ring29.color = "Rose Gold";
                ring29.brand = "Kalyan Jewellers";
                ring29.style = "Designer";
                ring29.occasion = "Party";
                ring29.gender = "Female";
                ring29.platingType = "Gold Plated";
                ring29.weight = 5.0;

                System.out.println(" The Material Type of Ring is " + ring29.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring29.gemstoneType);
                System.out.println(" The Ring Size is " + ring29.ringSize);
                System.out.println(" The Color of Ring is " + ring29.color);
                System.out.println(" The Brand of Ring is " + ring29.brand);
                System.out.println(" The Style of Ring is " + ring29.style);
                System.out.println(" The Occasion of Ring is " + ring29.occasion);
                System.out.println(" The Gender of Ring is " + ring29.gender);
                System.out.println(" The Plating Type of Ring is " + ring29.platingType);
                System.out.println(" The Weight of Ring is " + ring29.weight);
                System.out.println("--------------------------------------");

                Ring ring30 = new Ring();
                ring30.materialType = "Gold";
                ring30.gemstoneType = "Sapphire";
                ring30.ringSize = "6";
                ring30.color = "White";
                ring30.brand = "PC Jeweller";
                ring30.style = "Luxury";
                ring30.occasion = "Office";
                ring30.gender = "Male";
                ring30.platingType = "None";
                ring30.weight = 4.8;

                System.out.println(" The Material Type of Ring is " + ring30.materialType);
                System.out.println(" The Gemstone Type of Ring is " + ring30.gemstoneType);
                System.out.println(" The Ring Size is " + ring30.ringSize);
                System.out.println(" The Color of Ring is " + ring30.color);
                System.out.println(" The Brand of Ring is " + ring30.brand);
                System.out.println(" The Style of Ring is " + ring30.style);
                System.out.println(" The Occasion of Ring is " + ring30.occasion);
                System.out.println(" The Gender of Ring is " + ring30.gender);
                System.out.println(" The Plating Type of Ring is " + ring30.platingType);
                System.out.println(" The Weight of Ring is " + ring30.weight);
               
				
				
        }
}